### ISSUE TITLE
Plans for more great stuff

### ISSUE THREAD

**Issue by luss** [zilder/parquet_fdw#10]
any plans to keep working on this?

**Comment by zilder** [comment]
Hi @luss,

Currently my colleagues working on integrating `parquet_fdw` into our system. At the moment we have everything we need for our purposes. There are some things that would be nice to have but we can't due to limitations of `libparquet` (e.g. it doesn't yet support lists of structs).

I'll keep maintaining the project and add features eventually as someone needs them. If there are some features that you would like to see in `parquet_fdw` let me know.
